### ISSUE TITLE
Chrome does not support PNaCL in websites anymore since March 2018

### ISSUE THREAD

**Issue by informatorius** [FoldingAtHome/fah-nacl-client#81] opened 2018-03-22 13:54 UTC
Chrome does not support PNaCL in websites anymore since March 2018.

But Chrome Apps may still use PNaCL.

Can this be adapted to be a Chrome App instead?

**Comment by informatorius** [comment] 2018-03-22 18:12
Currently several users have the issue
https://foldingforum.org/viewtopic.php?f=95&t=30717

Google Chrome announced :>>We will remove support for PNaCl in the first quarter of 2018 everywhere except inside Chrome Apps and Extensions.<<
https://foldingforum.org/viewtopic.php?f=95&t=30047&p=295797&hilit=nacl#p295797

**Comment by informatorius** [comment] 2018-03-22 19:05
I found a workaround which brings us one step further:

Start chrome.exe with parameter --enable-nacl

But work unit still stuck at 0%.

**Comment by bb30994** [comment] 2018-03-22 23:47
I suspect that the PNACL client is still available for download (somewhere) even if there's a new one that's only NaCl.  I just downloaded a copy from a site recommended by Google Search.  

I can confirm the previous reports.  A WU is downloaded followed by a hang with the message **Warning: PNaCl module failure, fatal**

There used to be a page describing some options that needed to be set in Chrome.  I can't find that page.  Was that for the PNaCl client or the Native Client?  Do we still need to do that?

**Comment by informatorius** [comment] 2018-03-23 12:08
It looks like (P)NaCL would only still run on ChromeOS?

NaCl and PNaCl: Deprecation of the technologies described here has been announced for platforms other than ChromeOS. Please visit our migration guide for details.
https://developer.chrome.com/native-client/nacl-and-pnacl

**Comment by jcoffland** [comment] 2018-03-23 18:14
Chrome's migration guide says to rewrite your app using WebAssembly.  It looks like NaCl is a deadend.  We'll have to look into WebAssembly.  They claim on a 20% slowdown over native code.  It's likely worse for scientific code.   They do plan to support SIMD but without SIMD folding will be inefficient.  Although NaCl does support SIMD, in my testing it's not actually any faster than non-SIMD code.  The major benefit of WebAssembly would be that it runs in all major browsers.

**Comment by jcoffland** [comment] 2018-03-23 18:34
I fixed a problem I caused a few days ago which causes the stuck at 0% issue.  NaCl should be working now.  At least, I'm not having any problems in v64.0.3282.140 on Linux.

**Comment by informatorius** [comment] 2018-03-23 18:45
Yes Sir, it's working again on Windows 7 Chrome v65.0.3325.181

**Comment by bb30994** [comment] 2018-03-24 02:45
"or" ???
There may be two issues, one of which was fixed.

**Closed** 2018-03-26 09:25 UTC
